version: '3.4'

services:
  app:
    image: finreport
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./sec:/usr/sec:ro
volumes:
  sec: